# Generated by Django 5.2.1 on 2025-06-16 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0002_room_appliance_user_appliance_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliances', to='appliances.room'),
        ),
    ]
